// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType & DisallowNamespaces
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'fr'

export type Translation = RootTranslation & DisallowNamespaces

export type Translations = RootTranslation &
{
	app_signIn: NamespaceAppSignInTranslation,
	common: NamespaceCommonTranslation
}

type RootTranslation = {}

export type NamespaceAppSignInTranslation = {
	email: {
		/**
		 * E​m​a​i​l​ ​a​d​d​r​e​s​s
		 */
		label: string
		/**
		 * e​m​a​i​l​@​e​x​a​m​p​l​e​.​c​o​m
		 */
		placeholder: string
		/**
		 * S​i​g​n​ ​i​n​ ​w​i​t​h​ ​e​m​a​i​l
		 */
		button: string
	}
	/**
	 * o​r
	 */
	or: string
	/**
	 * M​o​r​e​ ​c​h​o​i​c​e​s​.​.​.
	 */
	more: string
	/**
	 * B​a​c​k​ ​t​o​ ​w​e​b​s​i​t​e
	 */
	'back-to-website': string
}

export type NamespaceCommonTranslation = {
	seo: {
		/**
		 * P​i​k​a​s​ ​T​e​m​p​l​a​t​e​ ​i​s​ ​a​ ​w​e​b​s​i​t​e​ ​t​h​a​t​ ​a​l​l​o​w​s​ ​y​o​u​ ​t​o​ ​s​t​a​r​t​ ​d​e​v​e​l​o​p​i​n​g​ ​y​o​u​r​ ​w​e​b​s​i​t​e​ ​i​n​ ​m​i​n​u​t​e​s​.
		 */
		description: string
	}
}

export type Namespaces =
	| 'app_signIn'
	| 'common'

type DisallowNamespaces = {
	/**
	 * reserved for 'app_signIn'-namespace\
	 * you need to use the `./app_signIn/index.ts` file instead
	 */
	app_signIn?: "[typesafe-i18n] reserved for 'app_signIn'-namespace. You need to use the `./app_signIn/index.ts` file instead."

	/**
	 * reserved for 'common'-namespace\
	 * you need to use the `./common/index.ts` file instead
	 */
	common?: "[typesafe-i18n] reserved for 'common'-namespace. You need to use the `./common/index.ts` file instead."
}

export type TranslationFunctions = {
	app_signIn: {
		email: {
			/**
			 * Email address
			 */
			label: () => LocalizedString
			/**
			 * email@example.com
			 */
			placeholder: () => LocalizedString
			/**
			 * Sign in with email
			 */
			button: () => LocalizedString
		}
		/**
		 * or
		 */
		or: () => LocalizedString
		/**
		 * More choices...
		 */
		more: () => LocalizedString
		/**
		 * Back to website
		 */
		'back-to-website': () => LocalizedString
	}
	common: {
		seo: {
			/**
			 * Pikas Template is a website that allows you to start developing your website in minutes.
			 */
			description: () => LocalizedString
		}
	}
}

export type Formatters = {}
