// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */

import { initFormatters } from './formatters.js';
import type { Locales, Translations } from './i18n-types.js';
import { loadedFormatters, loadedLocales, locales } from './i18n-util.js';

import en from './en/index.js';
import fr from './fr/index.js';

import en_app_signIn from './en/app_signIn/index.js';
import en_common from './en/common/index.js';
import fr_app_signIn from './fr/app_signIn/index.js';
import fr_common from './fr/common/index.js';

const localeTranslations = {
  en: {
    ...en,
    app_signIn: en_app_signIn,
    common: en_common,
  },
  fr: {
    ...fr,
    app_signIn: fr_app_signIn,
    common: fr_common,
  },
};

export const loadLocale = (locale: Locales): void => {
  if (loadedLocales[locale]) return;

  loadedLocales[locale] = localeTranslations[locale] as unknown as Translations;
  loadFormatters(locale);
};

export const loadAllLocales = (): void => locales.forEach(loadLocale);

export const loadFormatters = (locale: Locales): void =>
  void (loadedFormatters[locale] = initFormatters(locale));
