// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type {
  BaseTranslation as BaseTranslationType,
  LocalizedString,
} from 'typesafe-i18n';

export type BaseTranslation = BaseTranslationType & DisallowNamespaces;
export type BaseLocale = 'en';

export type Locales = 'en' | 'fr';

export type Translation = RootTranslation & DisallowNamespaces;

export type Translations = RootTranslation & {
  app_signIn: NamespaceAppSignInTranslation;
  common: NamespaceCommonTranslation;
};

type RootTranslation = {};

export type NamespaceAppSignInTranslation = {
  email: {
    /**
     * Email address
     */
    label: string;
    /**
     * email@example.com
     */
    placeholder: string;
    /**
     * Sign in with email
     */
    button: string;
  };
  /**
   * or
   */
  or: string;
  /**
   * More choices...
   */
  more: string;
  /**
   * Back to website
   */
  'back-to-website': string;
};

export type NamespaceCommonTranslation = {
  seo: {
    /**
     * Pikas Template is a website that allows you to start developing your website in minutes.
     */
    description: string;
  };
};

export type Namespaces = 'app_signIn' | 'common';

type DisallowNamespaces = {
  /**
   * reserved for 'app_signIn'-namespace\
   * you need to use the `./app_signIn/index.ts` file instead
   */
  app_signIn?: "[typesafe-i18n] reserved for 'app_signIn'-namespace. You need to use the `./app_signIn/index.ts` file instead.";

  /**
   * reserved for 'common'-namespace\
   * you need to use the `./common/index.ts` file instead
   */
  common?: "[typesafe-i18n] reserved for 'common'-namespace. You need to use the `./common/index.ts` file instead.";
};

export type TranslationFunctions = {
  app_signIn: {
    email: {
      /**
       * Email address
       */
      label: () => LocalizedString;
      /**
       * email@example.com
       */
      placeholder: () => LocalizedString;
      /**
       * Sign in with email
       */
      button: () => LocalizedString;
    };
    /**
     * or
     */
    or: () => LocalizedString;
    /**
     * More choices...
     */
    more: () => LocalizedString;
    /**
     * Back to website
     */
    'back-to-website': () => LocalizedString;
  };
  common: {
    seo: {
      /**
       * Pikas Template is a website that allows you to start developing your website in minutes.
       */
      description: () => LocalizedString;
    };
  };
};

export type Formatters = {};
